name: Setup Docs Site
run-name: ${{ github.actor }} is generating docs for github pages.
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: peaceiris/actions-mdbook@v1
      - run: cp ./changes.md ./docs_src/src/
      - name: generate-docs
        working-directory: ./docs_src
        run: mdbook build
      - uses: actions/upload-artifact@v3
        with:
          name: Generated Docs
          path: ./docs_src/book
